"""participants table

Revision ID: 06b234891101
Revises: 9b61c58a26ea
Create Date: 2020-05-20 22:04:12.971709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b234891101'
down_revision = '9b61c58a26ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('ethnicity', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('age >= 5 ', name='check_age_positive'),
    sa.ForeignKeyConstraint(['consent_id'], ['consent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consent', sa.Column('parent_first_name', sa.String(length=40), nullable=False))
    op.add_column('consent', sa.Column('parent_last_name', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'consent', ['signature'])
    op.drop_column('consent', 'childLastName')
    op.drop_column('consent', 'parentLastName')
    op.drop_column('consent', 'childFirstName')
    op.drop_column('consent', 'parentFirstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent', sa.Column('parentFirstName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('consent', sa.Column('childFirstName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('consent', sa.Column('parentLastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('consent', sa.Column('childLastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consent', type_='unique')
    op.drop_column('consent', 'parent_last_name')
    op.drop_column('consent', 'parent_first_name')
    op.drop_table('participants')
    # ### end Alembic commands ###
