"""empty message

Revision ID: 363ca05dddc1
Revises: c926051f456b
Create Date: 2020-05-28 18:40:44.285294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ca05dddc1'
down_revision = 'c926051f456b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_to_images',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'category_id')
    )
    op.add_column('participant_answers', sa.Column('answers', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('participant_answers', sa.Column('before_video', sa.Boolean(), nullable=False))
    op.drop_column('participant_answers', 'answer')
    op.drop_constraint('questions_img_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('img_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_img_id_fkey', 'questions', 'images', ['img_id'], ['id'])
    op.add_column('participant_answers', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('participant_answers', 'before_video')
    op.drop_column('participant_answers', 'answers')
    op.drop_table('questions_to_images')
    # ### end Alembic commands ###
