"""all tables

Revision ID: 5208ae7b7790
Revises: 06b234891101
Create Date: 2020-05-21 01:46:42.481012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5208ae7b7790'
down_revision = '06b234891101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_IAT_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('assigned_category', sa.String(length=40), nullable=False),
    sa.Column('unassigned_category', sa.String(length=40), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.CheckConstraint('assigned_category != unassigned_category', name='check_different_categories'),
    sa.ForeignKeyConstraint(['assigned_category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['unassigned_category'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_EAT_answers',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('choice_num', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_num', 'question_id'], ['question_choices.choice_num', 'question_choices.question_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'choice_num', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_EAT_answers')
    op.drop_table('participant_IAT_answers')
    # ### end Alembic commands ###
