"""empty message

Revision ID: 61b44ad63537
Revises: bdede68c2ab2
Create Date: 2020-05-20 19:41:36.148036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b44ad63537'
down_revision = 'bdede68c2ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_choices',
    sa.Column('choice_num', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('choice_num', 'question_id')
    )
    op.alter_column('questions', 'img_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'img_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('question_choices')
    # ### end Alembic commands ###
