"""new table category

Revision ID: b36faa5f2632
Revises: 988435237057
Create Date: 2020-05-19 23:48:08.386846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36faa5f2632'
down_revision = '988435237057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('metacategory', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('childFirstName', sa.String(length=80), nullable=False),
    sa.Column('childLastName', sa.String(length=80), nullable=False),
    sa.Column('parentFirstName', sa.String(length=80), nullable=False),
    sa.Column('parentLastName', sa.String(length=80), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('consent')
    op.drop_table('category')
    # ### end Alembic commands ###
