"""new table questions

Revision ID: bdede68c2ab2
Revises: 3bc9417bce3a
Create Date: 2020-05-20 00:54:51.794786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdede68c2ab2'
down_revision = '3bc9417bce3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('mc_single_answer', 'mc_multiple_answer', 'likert', 'binary', name='questiontype'), nullable=False),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
