"""empty message

Revision ID: dc1104c133d6
Revises: f75936ad1426
Create Date: 2020-05-29 18:26:56.540108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1104c133d6'
down_revision = 'f75936ad1426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_answers', sa.Column('img_link', sa.Text(), nullable=True))
    op.drop_constraint('participant_answers_img_id_fkey', 'participant_answers', type_='foreignkey')
    op.create_foreign_key(None, 'participant_answers', 'images', ['img_link'], ['link'])
    op.drop_column('participant_answers', 'img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_answers', sa.Column('img_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'participant_answers', type_='foreignkey')
    op.create_foreign_key('participant_answers_img_id_fkey', 'participant_answers', 'images', ['img_id'], ['id'])
    op.drop_column('participant_answers', 'img_link')
    # ### end Alembic commands ###
