"""remove-unique

Revision ID: e1b2cc5a44e5
Revises: 
Create Date: 2020-05-22 16:33:52.087705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b2cc5a44e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('metacategory', sa.Enum('profession', 'gender', 'hobby', 'social', name='metacategory'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_first_name', sa.String(length=40), nullable=False),
    sa.Column('parent_last_name', sa.String(length=40), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attribute', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('ethnicity', sa.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('age >= 6 and age <= 18', name='check_age_requirements'),
    sa.ForeignKeyConstraint(['consent_id'], ['consent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_IAT_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.Column('assigned_category', sa.String(length=40), nullable=False),
    sa.Column('unassigned_category', sa.String(length=40), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.CheckConstraint('assigned_category != unassigned_category', name='check_different_categories'),
    sa.ForeignKeyConstraint(['assigned_category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['unassigned_category'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('mc_single_answer', 'mc_multiple_answer', 'likert', 'binary', name='questiontype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_choices',
    sa.Column('choice_num', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('choice_num', 'question_id')
    )
    op.create_table('participant_EAT_answers',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('choice_num', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_num', 'question_id'], ['question_choices.choice_num', 'question_choices.question_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'choice_num', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_EAT_answers')
    op.drop_table('question_choices')
    op.drop_table('questions')
    op.drop_table('participant_IAT_answers')
    op.drop_table('participants')
    op.drop_table('images')
    op.drop_table('users')
    op.drop_table('consent')
    op.drop_table('categories')
    # ### end Alembic commands ###
